(() => {
  'use strict';
  const host = document.getElementById('sprint-path');
  const key = 'stacksprint-sprints-v1';
  let saved; try { saved = JSON.parse(localStorage.getItem(key) || '{}'); } catch { saved = {}; }
  if (!saved || typeof saved !== 'object') saved = {};
  let completed = Array.isArray(saved.completed) ? saved.completed.filter(x=>Number.isInteger(x)&&x>=0&&x<3) : [];
  completed = [...new Set(completed)];
  const today = () => new Date().toLocaleDateString('en-CA');
  let days = Array.isArray(saved.days) ? saved.days.filter(x=>typeof x==='string') : [];
  let storageError = false;
  function persist() { try { localStorage.setItem(key,JSON.stringify({completed,days})); } catch { storageError = true; } }
  const bot = '<span class="sprint-bot" aria-hidden="true"><i>• •</i><b>⌣</b><small>{ }</small></span>';
  function home() {
    host.innerHTML = `<div class="sprint-top"><span>YOUR POCKET CODING ARCADE</span><span>✦ ${completed.length*30} sprint XP</span></div><div class="sprint-intro"><div><p class="sprint-kicker">A LITTLE CURIOUS. A LITTLE BRAVER.</p><h1>Your next<br>“I made that!”<em>starts here.</em></h1><p>Three tiny challenges. One real skill.<br>Let’s turn “what does this do?” into “watch this.”</p><button class="sprint-primary" id="sprintResume">${completed.length===3?'Play a refresher':'Start a tiny win'} <span>→</span></button><p class="sprint-small">No hearts to lose. Mistakes are welcome.</p></div><div class="sprint-buddy">${bot}<p>Hey, I’m Bite.<br>Let’s figure it out together.</p></div></div><div class="sprint-route"><div class="sprint-unit"><span>UNIT 01 · THE FIRST SPARK</span><h2>Meet your building blocks</h2><p>Match it. Arrange it. Predict it.</p></div><div class="sprint-nodes">${['Connect the concepts','Build a little program','Read the future'].map((name,i)=>`<button class="sprint-node ${completed.includes(i)?'is-done':''}" data-mission="${i}" ${i>0&&!completed.includes(i-1)?'disabled':''}><span>${completed.includes(i)?'✓':['⌘','{ }','⚡'][i]}</span><strong>${name}</strong><small>${completed.includes(i)?'Replay anytime':i>0&&!completed.includes(i-1)?'Finish the previous challenge':'3-minute practice'}</small></button>`).join('')}</div><div class="sprint-reward"><span aria-hidden="true">✧</span><div><strong>${completed.length===3?'First Spark badge earned':'Your First Spark badge awaits'}</strong><p>${completed.length===3?'You connected the ideas. Now make something yours.':'Complete all three challenges to earn it.'}</p></div><a href="#python-course">Make it yours →</a></div></div><p class="sprint-small">${days.includes(today())?'You practiced today. Nice work! Come back when you’re ready.':'A fresh start is always welcome. Try one round today.'} ${storageError?'Progress could not be saved on this device.':''}</p>`;
    host.querySelector('#sprintResume').onclick=()=>open(completed.length===3?0:[0,1,2].find(i=>!completed.includes(i)));
    host.querySelectorAll('[data-mission]').forEach(b=>b.onclick=()=>open(Number(b.dataset.mission)));
  }
  const dialog=document.createElement('dialog');dialog.className='sprint-dialog';dialog.setAttribute('aria-label','Coding sprint');document.body.append(dialog);
  let mission=0,stage=0,attempts=0,started=0,chosen=null,matched=new Set(),order=[],finished=false;
  const pairs=[['HTML','Page structure'],['CSS','Visual styling'],['JavaScript','Interactive behavior'],['Database','Stored information']];
  const lines=['score = 3','score = score + 2','print(score)'];
  let terms=[],definitions=[];
  function shuffle(values){const a=[...values];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  function open(id){if(id>0&&!completed.includes(id-1))return;mission=id;stage=0;attempts=0;started=Date.now();chosen=null;matched=new Set();order=[];finished=false;terms=shuffle([0,1,2,3]);definitions=shuffle([0,1,2,3]);render();dialog.showModal();dialog.querySelector('h2').focus();}
  function frame(body,progress){dialog.innerHTML=`<header><button class="sprint-close" aria-label="Close sprint">×</button><progress value="${progress}" max="100" aria-label="Challenge progress"></progress><span>Practice ∞</span></header><div class="sprint-stage">${body}</div><footer><p role="status" aria-live="polite">Take your time. You’ve got room to experiment.</p></footer>`;dialog.querySelector('.sprint-close').onclick=()=>dialog.close();}
  function say(text){dialog.querySelector('[role="status"]').textContent=text;}
  function render(){
    if(mission===0){frame(`<p class="sprint-kicker">CONNECT THE CONCEPTS</p><h2 tabindex="-1">Every tool has a superpower.</h2><p>Tap a coding term, then its matching meaning.</p><div class="sprint-matches"><div>${terms.map(i=>`<button data-term="${i}" ${matched.has(i)?'disabled':''}>${pairs[i][0]}${matched.has(i)?' ✓':''}</button>`).join('')}</div><div>${definitions.map(i=>`<button data-definition="${i}" ${matched.has(i)?'disabled':''}>${pairs[i][1]}${matched.has(i)?' ✓':''}</button>`).join('')}</div></div>`,matched.size*25);
      dialog.querySelectorAll('[data-term]').forEach(b=>b.onclick=()=>{chosen=Number(b.dataset.term);dialog.querySelectorAll('[data-term]').forEach(t=>t.setAttribute('aria-pressed',String(t===b)));say(`Now choose the meaning of ${pairs[chosen][0]}.`);});
      dialog.querySelectorAll('[data-definition]').forEach(b=>b.onclick=()=>{if(chosen===null){say('Choose a coding term first.');return;}attempts++;if(Number(b.dataset.definition)===chosen){matched.add(chosen);chosen=null;if(matched.size===4)finish();else{render();say('Connected! One more piece of the picture.');}}else{say(`Not quite. ${pairs[chosen][0]} means ${pairs[chosen][1].toLowerCase()}. Try that pair again.`);}});
    }else if(mission===1){frame(`<p class="sprint-kicker">BUILD A LITTLE PROGRAM</p><h2 tabindex="-1">Give this program a beginning.</h2><p>Set the score to 3, add 2, then print it. Tap the Python lines in that order.</p><div class="sprint-code-slots">${order.length?order.map(i=>`<code>${lines[i]}</code>`).join(''):'Your program goes here…'}</div><div class="sprint-line-bank">${[2,0,1].map(i=>`<button data-line="${i}" ${order.includes(i)?'disabled':''}><code>${lines[i]}</code></button>`).join('')}</div><div class="sprint-controls"><button id="sprintUndo" ${!order.length?'disabled':''}>Undo last line</button><button class="sprint-primary" id="sprintCheck" ${order.length!==3?'disabled':''}>Check my program</button></div>`,order.length/3*80);
      dialog.querySelectorAll('[data-line]').forEach(b=>b.onclick=()=>{order.push(Number(b.dataset.line));render();});dialog.querySelector('#sprintUndo').onclick=()=>{order.pop();render();};dialog.querySelector('#sprintCheck').onclick=()=>{attempts++;if(order.join(',')==='0,1,2')finish();else say('A program runs from top to bottom. Set score before changing it; print after the change. Undo and try again.');};
    }else{const examples=[['print(3 + 2)',['32','5','3'],1,'These are numbers, so + adds them.'],['print("3" + "2")',['5','Error','32'],2,'Quotes make strings. + joins these two strings.'],['print(len("code"))',['4','5','code'],0,'len counts the four characters in code.']];const q=examples[stage];frame(`<p class="sprint-kicker">READ THE FUTURE · ${stage+1}/3</p><h2 tabindex="-1">What will Python print?</h2><pre>${q[0].replaceAll('<','&lt;')}</pre><div class="sprint-options">${q[1].map((v,i)=>`<button data-output="${i}">${v}</button>`).join('')}</div>`,stage/3*100);dialog.querySelectorAll('[data-output]').forEach(b=>b.onclick=()=>{attempts++;if(Number(b.dataset.output)===q[2]){dialog.querySelectorAll('[data-output]').forEach(t=>t.disabled=true);say('Exactly! '+q[3]);const next=document.createElement('button');next.className='sprint-primary';next.textContent=stage===2?'Finish sprint':'Next prediction →';next.onclick=()=>{stage++;if(stage===3)finish();else render();};dialog.querySelector('.sprint-stage').append(next);}else say('Not yet — '+q[3]+' Try again.');});}
  }
  function finish(){if(finished)return;finished=true;const fresh=!completed.includes(mission);if(fresh)completed.push(mission);if(!days.includes(today()))days.push(today());persist();const seconds=Math.max(1,Math.round((Date.now()-started)/1000));frame(`<div class="sprint-celebrate">${bot}<p class="sprint-kicker">SMALL WIN. REAL PROGRESS.</p><h2 tabindex="-1">You made it click!</h2><p>${['You connected four tools to their purpose.','You put a working program in order.','You traced numbers, strings, and a function.'][mission]}</p><div class="sprint-results"><span><b>${fresh?'+30':'✓'}</b>${fresh?'sprint XP':'refreshed'}</span><span><b>${attempts}</b>attempts</span><span><b>${seconds}s</b>your pace</span></div><p>${completed.length===3?'✧ First Spark badge earned. Ready to make something yours?':'Bite says: “The next little win is waiting.”'}</p><button class="sprint-primary" id="sprintDone">Back to my path →</button><p class="sprint-small">${fresh?'XP is awarded once per challenge.':'Replays reinforce skills without inflating XP.'} ${storageError?'Storage unavailable; progress is session-only.':''}</p></div>`,100);dialog.querySelector('#sprintDone').onclick=()=>dialog.close();dialog.querySelector('h2').focus();home();}
  dialog.addEventListener('close',()=>host.querySelector('#sprintResume').focus());
  home();
})();
